version: '3'
services:
  api-rest:
    image: rest-api-image
    build:
      context: ./ejercicioDevops  # La ruta al WORDIR
    ports:
      - "5000:5000"  # Puedes cambiar el puerto según sea necesario
    networks:
      - my-network

  app-web:
    image: app-web-image
    build:
      context: ./WEB  # La ruta al WORDIR
    ports:
      - "5050:5050" 
    depends_on:
      - api-rest  # Asegura que la API Spring Boot esté disponible antes de iniciar la aplicación Node.js
    networks:
      - my-network

networks:
  my-network: